[package]
name = "mcra"
version = "0.1.0"
edition = "2024"
description = "A library for computing minimum cost ressource allocation problems using column generation."

[dependencies]
gurobi = "0.3.4"
